require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/cable'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2

Rails:
  Enabled: true

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
  IndentationWidth: 2

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 200

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Metrics/AbcSize:
  Max: 65
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  Max: 60
  Exclude:
    - 'config/routes.rb'
    - 'lib/tasks/**/*'

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 60
  Exclude:
    - 'db/migrate/*'

Metrics/ModuleLength:
  Max: 300

Metrics/PerceivedComplexity:
  Max: 10

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/{2012,2013,2014,2015,2016,2017,2018}*.rb'

Rails/BulkChangeTable:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Rails/ReversibleMigration:
  Exclude:
    - 'db/migrate/{2012,2013,2014,2015,2016,2017,2018}*.rb'

Rails/SaveBang:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false
  Exclude:
    - 'lib/tasks/**/*'
    - 'db/migrate/*.rb'

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - production

Style/ClassAndModuleChildren:
  AutoCorrect: true

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/GuardClause:
  MinBodyLength: 3

Style/IfUnlessModifier:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/*'

Style/MultipleComparison:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SymbolArray:
  MinSize: 7
